
import { Inter } from 'next/font/google'
import Header from './components/Header/Header'
import "./globals.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Wordle Game',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Header />
        <div>
        {children}

        </div>

        
        </body>
    </html>
  )
}
